### ISSUE TITLE
sideberry renders a dark box when hover

### ISSUE THREAD

**Issue by danielphan2003** [drannex42/FirefoxSidebar#11]
example:
![2022-01-08_22-01-24](https://user-images.githubusercontent.com/34669737/148649421-ae1a72e7-d394-4e7c-b0ba-8528c8e415a7.png)

I suppose maybe sideberry wasn't able to catch up when the hover occurs?

**Comment by drannex42** [comment]
This is due to using a firefox dark theme with the light theme defaults. Please see the readme for information on what values to change to match your firefox theme! I am working on an automatic detection for light vs dark themes but nothing ready yet.
