### ISSUE TITLE
CSS only for visual changes without hover effect

### ISSUE THREAD

**Issue by h4wwk3ye** [drannex42/FirefoxSidebar#12]
Hey I created this issue on your Vivaldi mod https://github.com/drannex42/vivaldi-mods/issues/5. Can you please provide a version with only visual changes, thanks.

**Comment by drannex42** [comment]
If you only want visual changes, then install Sideberry, and load the sideberry-data.json file into your extension. Do not, install the userChrome.css file as that is what handles the responsive hiding feature. 

That should give you the Edge look without the auto hiding feature.
