### ISSUE TITLE
Weird padding issues (no-bookmarks-panel fix applied)

### ISSUE THREAD

**Issue by FallenChromium** [drannex42/FirefoxSidebar#13]
Hi there! First of all, I absolutely love your modification ❤️ , I've been searching for something like this for so long!

However, I have a little problem with it: notice how there's a little gap between the sidebar and the top bar
<img width="315" alt="Screenshot 2022-01-21 at 17 36 46" src="https://user-images.githubusercontent.com/43214067/150548263-58a85a78-86ca-4b85-afb7-717793be7071.png">
<img width="279" alt="Screenshot 2022-01-21 at 17 39 50" src="https://user-images.githubusercontent.com/43214067/150548280-a75c0c4d-e8ba-45a1-8dff-019b3ddc1737.png">

To be clear: I used bookmarks bar on new-tab only, but it wrecked the whole thing, because the panel was moving down every time I opened a new tab, so I disabled it and applied the fix mentioned in the readme (-40px). If you need any additional info, feel free to ping back :)

Thank you, overall it's working like a charm, I appreciate that you've gone through the effort to polish it that much!

P.S somehow, the dark theme didn't apply automatically, not sure what have gone wrong here, but I think that's because I'm using Librewolf

**Comment by drannex42** [comment]
Yes, It looks like you just need to change the setting of -40px to likely something closer to -41px or -42px. That should fix this issue if I am understanding you correctly.  

Dark mode is likely due to Librewolf, I think they changed the internal theme detection settings.

**Comment by FallenChromium** [comment]
You're right, I've fixed it with -42px. The dark mode started to work properly after I've disabled "Resist fingerprinting" librewolf settings, which is honestly a bad idea, so I've just copied over the dark css onto the light css manually, and now it works like a charm. Thanks for helping me out :)

**Comment by drannex42** [comment]
No problem! Happy you could figure it out! Especially that tip about fingerprinting -- make sense that they would disable that for security.
