### ISSUE TITLE
some issues with [sidebar background for bookmarks and history when light ff theme is enabled] + [close window button] + [toolbar icon spacing] 

### ISSUE THREAD

**Issue by ff-o** [drannex42/FirefoxSidebar#18]
Hello,

first of all thank you very much for your work. I love this repo.  Exactly what I wanted: sidebars like edge, but much better.
Works great, but I have some minor issues. (Win10, FF 98.0.1). 

https://imgur.com/a/rSDoAwt

1. 
When I switch to a light firefox theme, the background of the sidebar turns transparent, but only when showing bookmarks or history (no problem when sideberry is selected). No problem with a dark FF theme.

2. 
I noticed that the "close window" button seems to be hidden on the far right side, but you can still reach it. I dont' know, if this is intended. Really no big issue, but I can't figure out, how to change this.

3.
There is some weird empty spacing in the toolbar on the far right side, so I can't move the icons to the right side.
Doesn't bother me much, but I would like to know how to change it.

The only changes I made in userchrome.css is enabling @import url("./extensions/fix_hidden_bookmarks.css")

Thanks again

**Comment by drannex42** [comment]
Just looked again, you have a top bar, I would suggest disabling the csd utility by uncommenting that extension.

**Comment by ff-o** [comment]
Hey,
thank you for your quick replay.

Changing csd margin-right to 0px worked for issue 3, thanks.

"topbar"? Do you mean the title bar? It is unchecked in the "customize" menu.

I just tried installing this repo on another laptop, because I thought maybe this "transparent background" is a problem with my firefox installation.

On that other laptop was a light theme active during the installation of the repo plus sideberry. 
After installing the repo, the history/bookmarks sidebar is opaque as it should be, but when I change to any other theme it turns transparent.

It seems to be depended on the theme you had active during the installation of the repo (at least in my two cases) and if I change the initial theme, the hist./bookmarks sidebar turns transparent.
Maybe I am overlooking something.

**Comment by drannex42** [comment]
I just released a fix for the transparent background issue. You can find the release [here](https://github.com/drannex42/FirefoxSidebar/releases/tag/v12022.04.17)
