### ISSUE TITLE
how to change sidebery font size

### ISSUE THREAD

**Issue by advait404** [drannex42/FirefoxSidebar#19]
I am not sure how to change the tab text font size in sidebery. I am only able to change the font size of 'count of descendant fonts' using the left styles menu. Changing the font size under appearance setting also does not change the tab font size.

**Comment by drannex42** [comment]
--font-size in Sideberry -> Styles -> Sidebar (where the CSS code is). I decoupled this from the UI preference to make easier changes. 

Add your custom sizing to the custom section a few lines down.
