### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by royweisfeld** [drannex42/FirefoxSidebar#23]
Hey, I am having trouble with the dark mode appearance, I can change the settings to dark mode but the sidebar remains in light mode for some reason, haven't modified the config at all.

**Comment by drannex42** [comment]
You will need to modify the value in the Sideberry appearance style settings. Some dark themes (and operating systems) do not support the auto-dark settings and you will have to manually set this there.

**Comment by royweisfeld** [comment]
> You will need to modify the value in the Sideberry appearance style settings. Some dark themes (and operating systems) do not support the auto-dark settings and you will have to manually set this there.

Tried that multiple times in different places but just couldn't figure the correct value to change, reverting to my own settings and not the custom one for Sideberry allowed the dark mode to work
