### ISSUE TITLE
./extensions/window_controls.css is bugged

### ISSUE THREAD

**Issue by PhoenixCODE2322** [drannex42/FirefoxSidebar#25]
![image](https://user-images.githubusercontent.com/75798544/194731242-c7131273-ff24-43ef-9d97-bfcb364fd9c2.png)
As in the screenshot , the "close button is not visible".

```css
`/*
  Title: Drannex42's FirefoxSidebar / Vertical Tabs
  Description: Vertical tab design for Firefox with dynamic indentation::
    Sideberry and TreeStyleTabs (Legacy) themes available!
  Repository URL: https://github.com/drannex42/FirefoxSidebar
  Version: 12022.04.17
*/

/*
  Preferences / Settings ::
  Use this file to set your preferences this will save them in one place for easier future updating
  =========================================================================
*/

@import url("./prefs.css");

/* ========================================================================= */

/* Sidebar (Core) :: This file is for the sidebar implementation */
  @import url("./extensions/sidebar.css");

/*
  Extensions :: 
  To enable/disable specific extensions just comment/uncomment the line below. 
  =========================================================================
*/

  /* CSD / Window Controls */
    @import url("./extensions/window_controls.css");

  /* Bookmark Arrows :: add a little arrow next to folders in bookmarks toolbar */
    @import url("./extensions/bookmark_arrow.css");

  /* Superbox Removal :: heavily customize superbox (flat look, colors, smaller entries,...) */
    @import url("./extensions/superbox_removal.css");

  /* Avatar Size :: change the avatar size for the Firefox Account to what makes sense */
    @import url("./extensions/avatar_size.css");

  /* fix sidebar switcher if bookmarks toolbar is hidden */
    @import url("./extensions/fix_hidden_bookmarks.css");

  /* hide sidebar switcher */
    @import url("./extensions/hide_sidebar_switcher.css");

/* END EXTENSIONS ========================================================== */

/*
  Themes ::
  To enable/disable specific theme just comment/uncomment the line below.
  Please enable only one theme at a time!
  =========================================================================
*/

  /* GTK Adwaita */
    /* @import url("./themes/gtk_adwaita.css"); */

  /* GTK Breeze */
    /* @import url("./themes/gtk_breeze.css"); */

/* END THEMES ========================================================== */

/*
  Custom tweaks ::
  If you have any custom CSS for Firefox, place them in this file.
  =========================================================================
*/

  /* @import url("./custom.css"); */

/* ========================================================================= */
`
```

Currently i am using https://github.com/ranmaru22/firefox-vertical-tabs userChrome.css file contents which i pasted in your custom.css file.

i will post this screenshot below as i will have to restart this browser.

**Comment by PhoenixCODE2322** [comment]
![image](https://user-images.githubusercontent.com/75798544/194731307-c1de5a33-a1e1-49a4-baac-6b7ba95b929b.png)

**Comment by drannex42** [comment]
You will need to set your own CSD settings, this can be found in prefs.css. The issue is that every operating system has a different set of, well, settings for the window decorations (which is not fun!). 

You should just need to manually set the `--csd-width` to be larger, `--csd-top` to be lower, and the `csd-right` and/or `--csd-margin-right` values to get them into position. 

Yeah, this should be a lot easier, but for a truly cross-platform solution this was the best that we figured out (there are probably better ways),  This was a way to allow really specific formatting without having to go in and mess with the files. 

You might also need to add this to your custom.css file, but might not be needed?

```css
#titlebar {
appearance: none !important;
}
```

**Comment by PhoenixCODE2322** [comment]
Thank you it worked perfectly. For me who does not know css , it was very confusing. Please add this issue link to readme so new users can refer to this.

**Comment by drannex42** [comment]
I have added this to the release notes for the latest version. (https://github.com/drannex42/FirefoxSidebar/releases/tag/v12022.10.18) 

I will see about adding it to the ReadMe as well.
