### ISSUE TITLE
Audio svg change background color when using dark mode

### ISSUE THREAD

**Issue by advait404** [drannex42/FirefoxSidebar#26]
In the side berry setting file, the background for audio svg should be something other than #fff when in dark mode, since otherwise the 'music' icon color and background color become the same.

![image](https://user-images.githubusercontent.com/83760070/197141887-9e76a5a9-fc50-41db-8c1a-641bc67380f2.png)

eg, it can be changed to black:

.audio svg {
    background: #111111ff;
}

![image](https://user-images.githubusercontent.com/83760070/197142017-1e4675dd-a15a-4519-92f6-77237c31255d.png)

**Comment by drannex42** [comment]
I'll add this into the next release, thanks for reporting this!

**Comment by drannex42** [comment]
Added.
