### ISSUE TITLE
does not work properly with Firefox 107

### ISSUE THREAD

**Issue by advait404** [drannex42/FirefoxSidebar#29]
It looks like the sidebar does not detect the mouse properly, which does not trigger the opening of tabs properly. There is also some 'flickering' when my mouse is on top of a tab, like it keeps detecting and un-detecting the mouse.

sidebar.css may need some modifications to fix this.

https://user-images.githubusercontent.com/83760070/202835484-93911006-a853-4f2f-88a9-bc58f7b1425a.mp4

**Comment by drannex42** [comment]
I was sure that https://github.com/drannex42/FirefoxSidebar/releases/tag/v12022.10.18  fixed this, but I will will look into it.

What OS?

**Comment by CEOYap** [comment]
> I was sure that https://github.com/drannex42/FirefoxSidebar/releases/tag/v12022.10.18 fixed this, but I will will look into it.
> 
> What OS?
Latest version does fix the issue.

**Comment by drannex42** [comment]
Excellent! Very happy hear that. I'll close this out then.

Thanks for reporting it! If you notice anything else please let me know.

**Comment by advait404** [comment]
@drannex42 the hovering works perfectly when using sideberry, but it does not work properly with any other panel/extension using the sidebar.

https://user-images.githubusercontent.com/83760070/202878524-c2b9e636-fc7b-4a11-a342-a8bc7c09b68b.mp4




https://user-images.githubusercontent.com/83760070/202878568-bfb4a516-4916-4a94-a801-86ad4c062b21.mp4

**Comment by drannex42** [comment]
The second one tells me what is is. Thank you for that!

I'll see about getting an update sent out.

**Comment by drannex42** [comment]
This **should** be fixed with https://github.com/drannex42/FirefoxSidebar/releases/tag/v12022.11.18

**Comment by advait404** [comment]
@drannex42 the new update has an issue with the sidebar:
![image](https://user-images.githubusercontent.com/83760070/203215217-6326d381-ba79-474a-bc61-b7afa680bd17.png)

and somehow, its fixed by splitting the #sidebar-box {} from sidebar.css into 2 parts:
![image](https://user-images.githubusercontent.com/83760070/203215342-b8d2a548-2abf-4ed3-b74a-7ed69ab91197.png)

![image](https://user-images.githubusercontent.com/83760070/203215399-1b4e32ec-1f83-4784-a45d-67ab6175174b.png)

**Comment by LuXts** [comment]
https://github.com/drannex42/FirefoxSidebar/issues/29#issue-1456225890
Windows OS still has this issue.
Firefox 107.0

**Comment by drannex42** [comment]
@LuXts Did you try splitting that section into two? 

I do remember I split that into two for some reason in the past, but couldn't quite place it - this is probably that reason.

**Comment by drannex42** [comment]
> @drannex42 the new update has an issue with the sidebar: ![image](https://user-images.githubusercontent.com/83760070/203215217-6326d381-ba79-474a-bc61-b7afa680bd17.png)
> 
> and somehow, its fixed by splitting the #sidebar-box {} from sidebar.css into 2 parts: ![image](https://user-images.githubusercontent.com/83760070/203215342-b8d2a548-2abf-4ed3-b74a-7ed69ab91197.png)
> 
> ![image](https://user-images.githubusercontent.com/83760070/203215399-1b4e32ec-1f83-4784-a45d-67ab6175174b.png)

Do you want to submit a PR for that (splitting section in two), or just have me add it?

**Comment by advait404** [comment]
I think you can add it, since I am not familiar with  submitting PR requests.
