### ISSUE TITLE
Moving scrollbar to the left and reducing its width 

### ISSUE THREAD

**Issue by advait404** [drannex42/FirefoxSidebar#30]
I am using the below css in the sideberry settings to improve the scrollbar size and position. It can be useful to add this in the sideberry data file.

```
.scroll-container{ direction: rtl }
.scroll-container > .scrollable{ direction: ltr }
.scroll-container { scrollbar-width: thin }
```

**Comment by drannex42** [comment]
I am not so sure why this is needed, do you have a screencap of your system? When I add these to mine it moved everything to the right by 100+ pixels.

**Comment by advait404** [comment]
With the scrollbar size and position modification:

https://user-images.githubusercontent.com/83760070/203216082-210ecab8-e371-45ac-a1d6-99f557e0eccc.mp4

Without the scrollbar size and position modification:

https://user-images.githubusercontent.com/83760070/203216204-547e487c-c397-48bd-bf40-2187381192f4.mp4

I think it looks better, and it makes using the scrollbar easier since you reduce the movement needed by the mouse.

**Comment by drannex42** [comment]
I'll tinker on this, but personally not a huge fan of scrollbars for the most part. But this is the beauty of the system! You can add them and keep them.

As said, I'll tinker and see if I can up with a solution, perhaps a hover scrollbar that way it doesn't displace any items.
