### ISSUE TITLE
Issue with the sidebar and Sidebery menu (icon)

### ISSUE THREAD

**Issue by Marin-Kitagawa** [drannex42/FirefoxSidebar#36]
I have performed all the steps as mentioned in the `README.md` and yet the appearance is nothing like yours in terms of spacing etc. They look too crammed. I am not good at CSS. Could you please say why it appears like this and the remedy? I mean, which style block and the property must I change? I directly cloned yours into Chrome and imported Sidebery settings

Another problem is that I don't get the options you get when you clicked on the Sidebery icon. 

![image](https://user-images.githubusercontent.com/49131888/211615655-ba3348ce-c9c8-4941-a29d-de359b990b54.png)

**Comment by drannex42** [comment]
The video is from a much older version, the layout now is very similar, if not exactly, what you have there. I wasn't a fan of the amount of spacing in the initial versions and made it a bit more compact.

**Comment by drannex42** [comment]
You can additional spacing between buttons by modifying the "--tabs-spacing" CSS property in Sideberry. There's a small blurb on how to do that [here](https://github.com/drannex42/FirefoxSidebar#2-sideberry)

**Comment by Marin-Kitagawa** [comment]
Yes, I tried changing that. But the background shrinks. But when I adjust the tab height as mentioned in the comment, it grows down. But I am not able to bring both the icon and the text of the tab to the center

**Comment by drannex42** [comment]
This should be fixed with the new Sidebery v5 release. A rewrite of the styling is required.
