### ISSUE TITLE
Option to hide the titlebar aswell

### ISSUE THREAD

**Issue by RikKoedoot** [drannex42/FirefoxSidebar#37]
It would be nice to have an option to have hide the titlebar and have the window controll buttons on the same line as the urlbar, extensions, and menu button.

**Comment by drannex42** [comment]
This should already be enabled. You will need to disable the titlebar by customizing the layout of Firefox through the menu. This is a [decent guide](https://winaero.com/disable-blue-title-bar-firefox/) on how to do that. The CSD (those buttons in the titlebar) should automatically drop to their placement. You may need to modify the prefs.css to get them perfect though as every system sadly has different requirements.
