### ISSUE TITLE
Sidebar is buggy in Waterfox

### ISSUE THREAD

**Issue by sbstratos79** [drannex42/FirefoxSidebar#38]
I am using the exact same config for both LibreWolf and Waterfox, including Sideberry styles:
Librewolf
![Librewolf](https://user-images.githubusercontent.com/4395586/215312503-7356f07e-47fe-4ae0-a3b7-ce698ef89b0f.png)

Waterfox
![Waterfox](https://user-images.githubusercontent.com/4395586/215292051-37df15d3-278b-43e9-81b6-1e8cac7633ff.png)

EDIT: Now it's broken in Librewolf as well. And I am also facing #39 issue.

**Comment by drannex42** [comment]
This should be fixed in newer versions of the browsers, but I do not use them often. A rewrite is coming (#41) for Sidebery as they just released v5.
