### ISSUE TITLE
Sidebar overlaps firefox buttons

### ISSUE THREAD

**Issue by Goosegit11** [drannex42/FirefoxSidebar#40]
See this video:
https://0x0.st/HQKM.mkv

I'm using LibreWolf Firefox 114.0.1-2

**Comment by drannex42** [comment]
Closing this as thes should he fixed now.

**Comment by Goosegit11** [comment]
how do I update?

**Comment by drannex42** [comment]
Ah, it looks like on yours you need to enable either 1) the bookmarks bar, or 2) edit custom.css and uncomment the relevant section.

**Comment by Goosegit11** [comment]
![image](https://github.com/drannex42/FirefoxSidebar/assets/89806596/a5264ae4-1fdc-41c2-8616-5c6d8ade9882)
with bookmarks bar enabled

**Comment by drannex42** [comment]
Yes, this is expected. You should be able to continue seeing the back/forward/reload/address bar on top of the opened sidebar, this makes it easier to handle click inputs on hover for the navbar items in the sidebar, and makes it easier to open the sidebar, and then click back/forward then having to hover off the sidebar _and then_ go to the back/forward buttons.

**Comment by drannex42** [comment]
If you want to keep the bookmark bar off, but shift the sidebar down, then modify the `--menubar-height` variable in prefs.css.

**Comment by Goosegit11** [comment]
I don't think you quite understand my problem.
I've made a new video that shows everything clearly:
![Peek 2023-09-29 19-14](https://github.com/drannex42/FirefoxSidebar/assets/89806596/f299d080-1ee7-4181-a1b1-e45f9e00ffb0)

**Comment by drannex42** [comment]
Yes, that was a design decision, that way you can still see the back/forward buttons when the sidebar is open.

You will need to change the menubar offset position so that they do not overlap with the top bar buttons inside Sidebery.

**Comment by Goosegit11** [comment]
Can't you see the black thing? And the back, reload, forward buttons are see-through when I hover on bar... 

see how it looks in the README:

![image](https://github.com/drannex42/FirefoxSidebar/assets/89806596/1831e341-2271-44df-a000-e104b0cca16a)

and mine is ugly.. It's definitely not normal.

**Comment by drannex42** [comment]
You need to change the height of the sidebar, in the prefs.css file to lower your sidebar.

The black background on the sidebar heading: you need to change the background color to match your theme, as Firefox does not automatically change that (it's a limit imposed on their side). You can change that in prefs.css, instructions are included there. 

The back/reload/forward buttons being visible is a design decision, on purpose. The video in the readme is from an older version. We let you see them.

**Comment by Goosegit11** [comment]
How can I set it up like this?

![image](https://github.com/drannex42/FirefoxSidebar/assets/89806596/f54f93f7-baf3-4d96-a404-e30d0c369363)

So sidebar will be below reload/fast forward buttons
