### ISSUE TITLE
Visual glitches on navigation bar

### ISSUE THREAD

**Issue by merrkry** [drannex42/FirefoxSidebar#42]
![2023-09-21-08-27-00](https://github.com/drannex42/FirefoxSidebar/assets/124278440/2f846aef-1464-4573-a3f5-e3d052234444)

In the example video in README, the navigation displays the tab panel icon when folded. However, here a arrow overrides it and the transition is weired.

I am using Sidebery 5.0.1 with the newest fixes in #41.

**Comment by drannex42** [comment]
Yes. This is expected.

Video is from a very old version, with the new version the arrow takes its place, but I am looking into replacing it with the icon of the current existing tab stack.

**Comment by drannex42** [comment]
You can now set the general margin and nav button height individually if you want, that way you can center the arrow. I am still looking into replacing the arrow, but unsure if 1) possible 2) if I even really mind it once you center it properly. 

Check #41
