### ISSUE TITLE
Shifting page content when changing sidebar width

### ISSUE THREAD

**Issue by tk-nguyen** [drannex42/FirefoxSidebar#43]
I'm trying to change the width so I can use vertical containers layout.

Here's a video:

https://github.com/drannex42/FirefoxSidebar/assets/39090621/cda2e3ab-0d0c-4c7a-8445-c0889b52676a

I'm currenly using Sidebery v5 with [your custom styles](https://github.com/drannex42/FirefoxSidebar/issues/41#issuecomment-1726444433).

**Comment by drannex42** [comment]
If you want to change the width you'll need to make a few changes in your userChrome and in the Sidebery styles, you'll be looking for any values similar to 60px.
