### ISSUE TITLE
Browser overlaps sidebar

### ISSUE THREAD

**Issue by shortwavetrough** [drannex42/FirefoxSidebar#44]
Using the current version of this extension, and the newest version of Firefox. With FirefoxSidebar set to left (default), when hovering mouse over sidebar and it overlaps beginning of left side of browser, the browser then overlaps the sidebar. In other words, I can't use the sidebar refresh, back, forward, home, etc. buttons as the browser then overlaps the sidebar. The sidebar margins (?) may need to be expanded right so that the sidebar buttons can be clicked on. I can't seem to set margins for this in the css that works.

**Comment by drannex42** [comment]
Could you attach a screenshot or video showing this? I am having a hard time understanding what exactly you mean as it sounds like a multipart issue. Thanks.

**Comment by lucky13820** [comment]
![CleanShot 2023-12-31 at 00 10 54@2x](https://github.com/drannex42/FirefoxSidebar/assets/7293811/a8f8775b-8362-49ca-a5cb-6755997b1210)
I think I'm having the same issue, I could figure out how to make the sidebar appear under the CSD.
