### ISSUE TITLE
Sidebar Not Collapsing and Tabs Still on Top

### ISSUE THREAD

**Issue by chookity-pokk** [drannex42/FirefoxSidebar#45]
I followed the steps from the README and ran a `killall firefox` just to be safe but it seems like this isn't working as expected because in the screenshot below you can see that I still have the tabs on the top and my sidebar doesn't collapse. I am running the most up to date version of Firefox and just clone the repo this morning. I also double checked that the settings were changed in `about:config`.

![image](https://github.com/drannex42/FirefoxSidebar/assets/24358100/d610c91f-6936-47ae-b653-548212ddea55)

**Comment by drannex42** [comment]
Sounds like you haven't enabled the correct config in the about:config page, you'll need to allow access for usrrScripts and additions to the "Chrome" folder.

**Comment by drannex42** [comment]
> In Firefox navigate to about:config in your address bar and change the characteristic toolkit.legacyUserProfileCustomizations.stylesheets to true

**Comment by chookity-pokk** [comment]
That was set to true. I ended up solving this with [this](https://gitlab.com/greenbeast/firefox-config) config that I got a few years ago and don't really know the source.
