### ISSUE TITLE
Pinned tab is not flowing down as a column, instead its coming as a row

### ISSUE THREAD

**Issue by vraravam** [drannex42/FirefoxSidebar#46]
Using the latest version of this repo: d99c43774b56226834c273c131563dfa9625f58d
and sideberry v 5.0.0

PFA the screenshot: as you can see the 2nd pinned tab (primevideo) is flowing to the right (as a row)
<img width="349" alt="Screenshot 2023-12-18 at 1 03 02 PM" src="https://github.com/drannex42/FirefoxSidebar/assets/69629/6441d8ff-a2d8-4074-b2c0-1e2185c7d506">

**Comment by drannex42** [comment]
Yes, Sideberry changes their default configuration. You need to change how pinned tabs are displayed in the Sideberry settings, I am away from the PC at the moment, but I believe you can find the setting under "Pineed Tabs" or "Tabs".

**Comment by vraravam** [comment]
Closing since the issue got resolved. I tried the above, but that didn't work. Then recreated my FF profile and installed the extension and this chrome settings, and things suddenly started working. Not brave enough to "corrupt" and do a proper RCA
