### ISSUE TITLE
Option do change the time it takes for the sidebar to open on hover

### ISSUE THREAD

**Issue by Aphemra** [drannex42/FirefoxSidebar#54]
I recently just switched to Firefox from Edge and this Sidebar mod has been a godsend! Just a small request/question.

I am not sure if this is already possible and I'm missing it or if it is a lack of functionality due to this being purely CSS in nature.

But Edge currently has a slight delay before opening the sidebar, which allows for the switching of tabs by clicking on the icons representing them instead of having it open up and then click on them.

This is really jarring when using pinned tabs since the pinned tabs auto-align to the top of the sidebar horizontally as soon as it opens. Would be great if this is possible with just CSS.

**Comment by drannex42** [comment]
I've tried, and failed, at implementing something along those lines. I'm not sure if it would be possible with the limitations of their flavour of CSS and how Firefox handles animations, transitions, and keyframes in the browser interface. Strangely enough, they don't use standard CSS or even HTML in their layout engine... Which would make the most sense... for a browser. Sense and Mozilla rarely go hand-in-hand, so it's just par for the course. 

There was a short period between FF v110 and v118 (?) where we had a solution, but they seem to have pulled that capability for some reason. 

---

**On Pinned tabs**, you need to set Sidebery to "show titles" in the pinned tab settings, this will make it look like a normal tab (just without a close button, and a small border under). Not sure why that wasn't saved in the sidebery prefs file. I'll take a look. 

---

Closing this for now.
